//
//  MoviesNames.swift
//  MovieQuotes
//
//  Created by admin on 21/12/2021.
//

import Foundation

struct MoviesNames {
    let moviesNameList = [
        "10 Cloverfield Lane",
        "12 Angry Men",
        "12 Monkeys",
        "2001 Maniacs",
        "2001: A Space Odyssey",
        "2010: The Year We Make Contact",
        "25th Hour",
        "28 Weeks Later",
        "31",
        "300",
        "8 Women",
        "8½",
        "A Nightmare on Elm Street (Freddy Krueger Series)",
        "Abbott and Costello Meet Frankenstein",
        "Absentia",
        "Adaptation",
        "Addams Family, The",
        "Adventures of Buckaroo Banzai, The",
        "After Hours",
        "After Life",
        "Against the Wall",
        "Aguirre, Wrath of God",
        "Akira",
        "Aladdin",
        "Alan Partridge Alpha Papa",
        "Alice in Wonderland",
        "Alien (Series)",
        "Alita Battle Angel",
        "All About Eve",
        "All Cheerleaders Die",
        "All the Boys Love Mandy Lane",
        "Alphaville",
        "Altered States",
        "Amadeus",
        "Amazon Women on the Moon",
        "Amelie",
        "American Beauty",
        "American Buffalo",
        "American History X",
        "American Honey",
        "American Mary",
        "American Movie",
        "American Psycho",
        "American Scream, The",
        "American Sniper",
        "An American Werewolf in London",
        "An Evening With Beverly Luff Linn",
        "Angst",
        "Annie Hall",
        "Anomalisa",
        "Antichrist",
        "Apartment, The",
        "Apt Pupil",
        "Aristocrats, The",
        "Artist, The",
        "As Above, So Below",
        "As the Gods Will",
        "Assassination Nation",
        "Assault on Precinct 13",
        "Assistant, The",
        "Atomic Cafe, The",
        "Atomic Zombies",
        "Attack of the Killer Tomatoes",
        "Attack the Block",
        "Attic Expeditions, The",
        "Audition",
        "Auto Focus",
        "Autopsy of Jane Doe, The",
        "Avatar",
        "Babadook, The",
        "Baby Blood",
        "Back to Black: The V/H/S Horror Franchise and the Thrill of a Mystery Tape",
        "Bad Batch, The",
        "Bad Biology",
        "Bad Boys",
        "Bad Education",
        "Bad Girls Go to Hell",
        "Bad Grandpa",
        "Bad Lieutenant",
        "Bad Santa",
        "Baise-moi",
        "Bambi",
        "Bandersnatch",
        "Barbarella",
        "Barbershop",
        "Barking Dogs Never Bite",
        "Barry Lyndon",
        "Bartleby",
        "Barton Fink",
        "Basic Instinct",
        "Basket Case",
        "Baskin",
        "Battle Royale",
        "Beach Bum, The",
        "Beach, The",
        "Beasts of the Southern Wild",
        "Bedazzled",
        "Beetlejuice",
        "Beguiled, The",
        "Behind the Curve",
        "Behind the Mask",
        "Being John Malkovich",
        "Belko Experiment, The",
        "Belladonna of Sadness",
        "Belle de Jour",
        "Bellflower",
        "Berberian Sound Studio",
        "Better Watch Out",
        "Betting on Zero",
        "Beyond the Valley of the Dolls",
        "Beyond, The",
        "Bicentennial Man",
        "Big Bad Wolves",
        "Big Bird Cage, The",
        "Big Fan",
        "Big Lebowski, The",
        "Big Man Japan",
        "Big Sick, The",
        "Big Top Pee-Wee",
        "Big Trouble in Little China",
        "Bill and Teds Excellent Adventure",
        "Billy Jack",
        "Bird with the Crystal Plumage, The",
        "Birdman",
        "Bittersweet Life, A",
        "Black Cauldron, The",
        "Black Christmas",
        "Black Dynamite",
        "Black Snake Moan",
        "Black Swan",
        "Blacula",
        "Blade Runner",
        "Blade Runner 2049",
        "Blade of the Immortal",
        "Blair Witch",
        "Blair Witch Project, The",
        "Blazing Saddles",
        "Blindspotting",
        "Bling Ring, The",
        "Blob, The",
        "Blood Feast",
        "Blood Feast 2",
        "Blood Simple",
        "Blood and Black Lace",
        "Blood and Bone",
        "Bloody Birthday",
        "Blown Away",
        "Blowup",
        "Blue Jasmine",
        "Blue My Mind",
        "Blue Ruin",
        "Blue Velvet",
        "Blues Brothers, The",
        "Body Double",
        "Bokeh",
        "Bone Tomahawk",
        "Booksmart",
        "Boondock Saints",
        "Border",
        "Bound",
        "Boxing Helena",
        "Brain Damage",
        "Brave Little Toaster, The",
        "Brawl in Cell Block 99",
        "Brazil",
        "Breakfast Club, The",
        "Breaking the Waves",
        "Bride of Frankenstein",
        "Bright Falls",
        "Brigsby Bear",
        "Bringing Out the Dead",
        "Bronson",
        "Brood, The",
        "Brother From Another Planet, The",
        "Brothers Grimm, The",
        "Bubba Ho-tep",
        "Bubble",
        "Bucket of Blood, A",
        "Buffalo 66",
        "Buffy the Vampire Slayer",
        "Bug",
        "Bullitt",
        "Bulworth",
        "Buried",
        "Burn After Reading",
        "Burnt Offerings",
        "Burying the Ex",
        "Cabin Fever",
        "Cabin Fever 2",
        "Cabin in the Woods, The",
        "Cabinet of Dr. Caligari, The",
        "Cache",
        "Calvaire",
        "Calvary",
        "Cam",
        "Candyman",
        "Cannibal Holocaust",
        "Casino Royale",
        "Catch 22",
        "Catfish",
        "Cecil B Demented",
        "Celebration, The",
        "Cell, The",
        "Cemetery Junction",
        "Cemetery Man",
        "Centurion",
        "Chan is Missing",
        "Changeling, The",
        "Charley Varrick",
        "Chasing Amy",
        "Chelsea Girls",
        "Child's Play (Chucky Series)",
        "Children of Men",
        "Children of the Corn (Series)",
        "Children, The",
        "Chillerama",
        "Chinatown",
        "Chopping Mall",
        "Christine",
        "Christmas on Mars",
        "Chronicle",
        "Chungking Express",
        "Citizen Kane",
        "Citizenfour",
        "City of the Living Dead",
        "Class of 1984",
        "Class of 1999",
        "Clear and Present Danger",
        "Clerks",
        "Climax",
        "Clockers",
        "Clockwork Orange, A",
        "Closer",
        "Cloud Atlas",
        "Cloverfield",
        "Clown",
        "Clue",
        "Cockfighter",
        "Coffy",
        "Coherence",
        "Cold Fish",
        "Cold Souls",
        "Cold in July",
        "Collateral",
        "Color Out of Space",
        "Colossal",
        "Colossus: The Forbin Project",
        "Company Men, The",
        "Compliance",
        "Computer Chess",
        "Conan the Barbarian",
        "Confessions of a Dangerous Mind",
        "Congress, The",
        "Constantine",
        "Contact",
        "Contagion",
        "Conversation, The",
        "Cooties",
        "Cop Car",
        "Coraline",
        "Corpse Bride",
        "Cosmopolis",
        "Cottage, The",
        "Craft, The",
        "Crank",
        "Crank 2: High Voltage",
        "Crash",
        "Crawl",
        "Creep",
        "Creepshow",
        "Crimes and Misdemeanors",
        "Criminal Lovers",
        "Crimson Peak",
        "Critters (Series)",
        "Cronos",
        "Crooklyn",
        "Cross of Iron",
        "Crow, The",
        "Cry-Baby",
        "Cube",
        "Cult of Chucky",
        "Cure",
        "Curious Case of Benjamin Button, The",
        "Curse of Chucky",
        "Cuties",
        "DOA: Dead or Alive",
        "Da 5 Bloods",
        "Dagon",
        "Daisies",
        "Dancer in the Dark",
        "Dangerous Method, A",
        "Dark City",
        "Dark Crystal, The",
        "Dark Horse",
        "Dark Star",
        "Darkon",
        "Dawn of the Dead",
        "Day Reagan Was Shot, The",
        "Dazed and Confused",
        "De-Lovely",
        "Dead Man",
        "Dead Ringers",
        "Dead Zone, The",
        "Death Becomes Her",
        "Death Race 2000",
        "Death of a President",
        "Death to Smoochy",
        "Deep Red",
        "Deep Rising",
        "Deer Hunter, The",
        "Deerskin",
        "Delicatessen",
        "Deliver Us From Evil",
        "Deliverance",
        "Dementia 13",
        "Demolition Man",
        "Demon Seed",
        "Demonlover",
        "Dentist, The",
        "Departed, The",
        "Descent, The",
        "Desperado",
        "Desperate Living",
        "Destroyer",
        "Detroit Rock City",
        "Devil's Backbone, The",
        "Devil's Rejects, The",
        "Devil’s Candy, The",
        "Die Hard",
        "Dig!",
        "Digging Up the Marrow",
        "Director's Cut",
        "Dirty Shame, A",
        "Dirty Work",
        "Django",
        "Django Unchained",
        "Do the Right Thing",
        "Dog Day Afternoon",
        "Dog Soldiers",
        "Dogtooth",
        "Dogville",
        "Don't Breathe",
        "Don't Look Now",
        "Donkey Skin",
        "Doomsday",
        "Dope",
        "Double Indemnity",
        "Doubt",
        "Downfall",
        "Dr. Horrible's Sing-Along Blog",
        "Dr. No",
        "Dracula",
        "Dracula AD 1972",
        "Drag Me to Hell",
        "Drive",
        "Drive Angry",
        "Driver, The",
        "Drop Dead Gorgeous",
        "Duck Soup",
        "Dude Bro Party Massacre 3",
        "Duel",
        "Dummy",
        "Dune",
        "Earrings of Madame de..., The",
        "Eastern Promises",
        "Easy Rider",
        "Ed Wood",
        "Eden Lake",
        "Edward Scissorhands",
        "Eighth Grade",
        "El Topo",
        "Elephant",
        "Elephant Man, The",
        "Elle",
        "Elvira's Haunted Hills",
        "Elvira: Mistress of the Dark",
        "Emma",
        "End of August at the Hotel Ozone, The",
        "End of Watch",
        "Endless, The",
        "Enemies of Reason, The",
        "Enemy",
        "Enter the Dragon",
        "Equilibrium",
        "Eraserhead",
        "Escape from LA",
        "Escape from NY",
        "Escape from Tomorrow",
        "Eternal Sunshine of the Spotless Mind",
        "Even Dwarfs Started Small",
        "Everly",
        "Everybody Wants Some",
        "Excision",
        "Exit Through the Gift Shop",
        "Exorcism of Emily Rose, The",
        "Expelled",
        "Expendables, The",
        "Exterminating Angel, The",
        "Extra Ordinary",
        "Eyes Wide Shut",
        "Eyes Without a Face",
        "Eyes of My Mother, The",
        "FP, The",
        "Faculty, The",
        "Fahrenheit 9/11",
        "Fallen Angels",
        "Falling Down",
        "Fantastic Mr. Fox",
        "Fantastic Planet",
        "Fargo",
        "Fast Food Nation",
        "Faster, Pussycat! Kill! Kill!",
        "Fatal Attraction",
        "Fear and Loathing in Las Vegas",
        "Fear of a Black Hat",
        "Feast",
        "Female Trouble",
        "Fermat’s Room",
        "Field in England, A",
        "Fifth Element, The",
        "Fight Club",
        "Final Destination (Series)",
        "Firestarter",
        "First Cow",
        "First Reformed",
        "Fistful of Dollars, A",
        "Fitzcarraldo",
        "Flock of Dodos",
        "Fly, The",
        "Fog, The",
        "Follow That Bird",
        "Footloose",
        "For Your Consideration",
        "For a Few Dollars More",
        "Forbidden Zone",
        "Force Majeure",
        "Forrest Gump",
        "Fountain, The",
        "Fountainhead, The",
        "Four Flies on Grey Velvet",
        "Four Rooms",
        "Fourth Kind, The",
        "Foxy Brown",
        "Frances Ha",
        "Frankenstein",
        "Freaks",
        "Freddy vs Jason",
        "Freeway",
        "Friday",
        "Friday the 13th (Jason Series)",
        "Fright Night",
        "Frighteners, The",
        "From Beyond",
        "From Dusk Till Dawn",
        "From Hell",
        "Frost Nixon",
        "Frozen",
        "Fruitvale Station",
        "Full Metal Jacket",
        "Funeral, The",
        "Funny Games",
        "Fur",
        "Future, The",
        "Galaxy Quest",
        "Galaxy of Terror",
        "Game, The",
        "Gamera: Guardian of the Universe",
        "Gattaca",
        "Gentlemen Prefer Blondes",
        "Get Carter",
        "Get Duked!",
        "Get On the Bus",
        "Get Out",
        "Ghost Dog: The Way of the Samurai",
        "Ghost Story, A",
        "Ghost World",
        "Ghost in the Shell",
        "Ghosts of Mars",
        "Ghoulies (Series)",
        "Giallo",
        "Ginger Snaps (Series)",
        "Ginger and Rosa",
        "Girl, Interrupted",
        "Girlfriend Experience, The",
        "Giuseppe Makes A Movie",
        "Glen or Glenda",
        "Glengarry Glen Ross",
        "God Bless America",
        "God Who Wasn't There, The",
        "Godfather, The",
        "Godzilla: Final Wars",
        "Gojira",
        "Gold Diggers of 1933",
        "Goldeneye",
        "Gone Girl",
        "Gone with the Wind",
        "Good Neighbor, The",
        "Good Night and Good Luck",
        "Good Time",
        "Good, the Bad and the Ugly, The",
        "Gore Gore Girls, The",
        "Gothic",
        "Graphic Sexual Horror",
        "Grave of the Fireflies",
        "Greasy Strangler, The",
        "Great Dictator, The",
        "Great Santini, The",
        "Green Inferno, The",
        "Green Room",
        "Greener Grass",
        "Gremlins",
        "Gremlins 2",
        "Grizzly Man",
        "Guest, The",
        "Guilty, The",
        "Gummo",
        "Hail Satan",
        "Hairspray",
        "Halloween",
        "Halloween (Michael Myers Series)",
        "Halloween 2",
        "Hamlet 2",
        "Handmaiden, The",
        "Hands on a Hardbody",
        "Hanna",
        "Hannah and Her Sisters",
        "Happening, The",
        "Happiness",
        "Happiness of the Katakuris, The",
        "Happy Accidents",
        "Happy Go Lucky",
        "Hard Candy",
        "Hard Rock Zombies",
        "Hard Ticket to Hawaii",
        "Hardcore Henry",
        "Harry Brown",
        "Harvey",
        "Hatchet",
        "Hatchet 2",
        "Hatchet 3",
        "Hateful Eight, The",
        "Haunted World of El Superbeasto, The",
        "Haunting, The",
        "Hausu",
        "Haywire",
        "He Died with a Felafel in His Hand",
        "He Got Game",
        "Head",
        "Heartbeeps",
        "Hearts and Minds",
        "Heat",
        "Heavenly Creatures",
        "Heavy Metal",
        "Hell Ride",
        "Hellraiser (Pinhead Series)",
        "Henry Fool",
        "Henry: Portrait of a Serial Killer",
        "Her",
        "Here Comes the Devil",
        "Hereditary",
        "Hero",
        "High Tension",
        "Hills Have Eyes, The",
        "His House",
        "History of Violence, A",
        "Hitcher, The",
        "Hits",
        "Hobo with a Shotgun",
        "Hocus Pocus",
        "Holy Motors",
        "Honey Boy",
        "Honey I Shrunk the Kids",
        "Honeymoon",
        "Horns",
        "Horror of Dracula",
        "Horse Girl",
        "Host, The",
        "Hostage",
        "Hostel",
        "Hostel 2",
        "Hot Rod",
        "Hot Tub Time Machine",
        "House",
        "House That Jack Built, The",
        "House by the Cemetery, The",
        "House of 1000 Corpses",
        "House of Wax (1953)",
        "House of Wax (2005)",
        "House of the Devil, The",
        "House on Haunted Hill",
        "House on Sorority Row, The",
        "House with a Clock in Its Walls, The",
        "How to Lose a Guy in Ten Days",
        "How to Talk to Girls at Parties",
        "Howl's Moving Castle",
        "Hudsucker Proxy, The",
        "Human Centipede 2, The",
        "Human Centipede 3, The",
        "Human Centipede, The",
        "Human Tornado, The",
        "Humanoids from the Deep",
        "Hunchback of Notre Dame, The",
        "Hunger",
        "Hunt for Red October, The",
        "Hunt, The",
        "I Know What You Did Last Summer (Series)",
        "I Saw the Devil",
        "I Stand Alone",
        "I'm a Cyborg But That's Ok",
        "Ice Cream Man",
        "Ichi the Killer",
        "Idiocracy",
        "Idiots, The",
        "Idle Hands",
        "If Beale Street Could Talk",
        "Imposter, The",
        "In a Valley of Violence",
        "In the Face of Evil",
        "In the Mouth of Madness",
        "Indie Game",
        "Industrial Symphony No. 1",
        "Inglourious Basterds",
        "Ingrid Goes West",
        "Inland Empire",
        "InnerSpace",
        "Innkeepers, The",
        "Inside",
        "Inside Llewyn Davis",
        "Insider, The",
        "Insidious",
        "Insomnia",
        "Intacto",
        "Interview With the Vampire",
        "Intolerable Cruelty",
        "Intruder",
        "Invaders from Mars",
        "Invasion of the Body Snatchers",
        "Invention of Lying, The",
        "Invincible",
        "Invitation, The",
        "Iron Giant, The",
        "Iron Sky",
        "Irreversible",
        "Isle of Dogs",
        "It",
        "It Follows",
        "It Happened Here",
        "It's Such a Beautiful Day",
        "JCVD",
        "Jack Brooks Monster Slayer",
        "Jack Ryan: Shadow Recruit",
        "Jackie",
        "Jackie Brown",
        "Jacob's Ladder",
        "Jaws (Series)",
        "Jennifer's Body",
        "Jerk, The",
        "Jesus Camp",
        "Jigsaw",
        "Jim and Andy: The Great Beyond",
        "Jodorowsky's Dune",
        "Joe",
        "John Carpenter's Vampires",
        "John Dies at the End",
        "John Wick",
        "Jonestown",
        "Joy Ride",
        "Julien Donkey-Boy",
        "Jupiter Ascending",
        "Jurassic Park",
        "K-PAX",
        "Kajillionaire",
        "Keep An Eye Out",
        "Ken Park",
        "Kids",
        "Kiki's Delivery Service",
        "Kill Bill",
        "Kill Bill 2",
        "Kill List",
        "Killer Klowns from Outer Space",
        "Killing Bono",
        "Killing Room, The",
        "Killing of a Sacred Deer, The",
        "Killing, The",
        "Kindergarten Cop",
        "King of Kong, The",
        "King of New York",
        "Kinky Boots",
        "Kiss Kiss, Bang Bang",
        "Klown",
        "Knives Out",
        "Knock Knock",
        "Krampus",
        "Kubo and the Two Strings",
        "Kumiko, The Treasure Hunter",
        "Kuso",
        "L'Atalante",
        "L.A. Story",
        "LA Confidential",
        "La Grande Bouffe",
        "Ladykillers, The",
        "Last Action Hero",
        "Last Black Man in San Francisco, The",
        "Last Exorcism, The",
        "Last Man on Earth, The",
        "Lawnmower Man, The",
        "League of Extraordinary Gentlemen",
        "Leave it to Beavers",
        "Ledge, The",
        "Legend",
        "Lego Movie, The",
        "Leprechaun (Series)",
        "Let Me Make You a Martyr",
        "Let the Right One In",
        "Libertine, The",
        "Lighthouse, The",
        "Limey, The",
        "Lion King, The",
        "Little Monsters",
        "Little Nemo",
        "Little Princess, A",
        "Little Shop of Horrors, The",
        "Living Daylights, The",
        "Lo and Behold",
        "Lobster, The",
        "Logan Lucky",
        "Logan's Run",
        "Look",
        "Looney Tunes: Back in Action",
        "Looper",
        "Loose Change",
        "Lord of War",
        "Lords of Salem, The",
        "Lost Highway",
        "Lost in Translation",
        "Love",
        "Love Witch, The",
        "Loved Ones, The",
        "Lovely Bones, The",
        "Lowlife",
        "Lucifer Rising",
        "Lure, The",
        "M",
        "Machete",
        "Machete Kills",
        "Machine Girl, The",
        "Machinist, The",
        "Mad Max: Fury Road",
        "Magic Magic",
        "Magic Mike",
        "Magnolia",
        "Malignant",
        "Man From Earth, The",
        "Man Who Killed Don Quixote, The",
        "Man Who Wasn’t There, The",
        "Man on Fire",
        "Man on Wire",
        "Man with the Golden Arm, The",
        "Man with the Iron Fists, The",
        "Mandy",
        "Manhattan",
        "Manhattan Murder Mystery",
        "Manhunter",
        "Maniac",
        "Maniac Cop (Series)",
        "Mank",
        "Maps to the Stars",
        "Marihuana",
        "Mars Attacks",
        "Mars Needs Women",
        "Martian, The",
        "Martyrs",
        "Mary and Max",
        "Master, The",
        "Matador",
        "Matador, The",
        "Matinee",
        "Matrix, The",
        "May",
        "Mayhem",
        "McVeigh Tapes, The",
        "Me and You and Everyone We Know",
        "Mean Creek",
        "Mean Girls",
        "Meet the Feebles",
        "Melancholia",
        "Melinda and Melinda",
        "Memento",
        "Memoirs of an Invisible Man",
        "Memories of Murder",
        "Metropolitan",
        "Michael Moore Hates America",
        "Midsommar",
        "Million Dollar Hotel, The",
        "MirrorMask",
        "Misery",
        "Mist, The",
        "Mister Frost",
        "Mister Lonely",
        "Moebius",
        "Moneyball",
        "Monster Man",
        "Monster Squad, The",
        "Monster's Ball",
        "Monsters",
        "Moon",
        "Moonlight",
        "Moonraker",
        "Moonrise Kingdom",
        "Mother",
        "Mother!",
        "Ms. 45",
        "Mulberry Street",
        "Mulholland Drive",
        "Mummy, The",
        "Muppet Movie, The",
        "Murder By Death",
        "Murderball",
        "My Bloody Valentine",
        "My Dinner with Andre",
        "My Life as a Zucchini",
        "My Neighbor Totoro",
        "My Son, My Son What Have Ye Done",
        "Mysterious Skin",
        "Naked Lunch",
        "Nashville",
        "Natural Born Killers",
        "Near Dark",
        "Neon Demon, The",
        "Network",
        "New Jack City",
        "Next",
        "Nice Dreams",
        "Nice Guys, The",
        "Night at the Golden Eagle",
        "Night in Casablanca, A",
        "Night of the Comet",
        "Night of the Creeps",
        "Night of the Demons (Series)",
        "Night of the Hunter, The",
        "Nightcrawler",
        "Nightmare Before Christmas, The",
        "Nights of Cabiria",
        "Ninotchka",
        "No Country for Old Men",
        "Nocturnal Animals",
        "North By Northwest",
        "Northfork",
        "Nosferatu the Vampyre",
        "Nothing",
        "Nymphomaniac",
        "O Brother, Where Art Thou?",
        "Office Space",
        "Oh, God!",
        "Oldboy",
        "Once Upon a Time in the West",
        "One Flew Over the Cuckoo's Nest",
        "Only God Forgives",
        "Only Lovers Left Alive",
        "Open Windows",
        "Opera",
        "Orca: The Killer Whale",
        "Orgazmo",
        "Orphan",
        "Out of the Past",
        "Overlord",
        "Overnight, The",
        "P2",
        "Pacific Rim",
        "Paddington",
        "Palindromes",
        "Palm Springs",
        "Papillon",
        "Paranormal Activity (Series)",
        "Paranorman",
        "Party Monster",
        "Pather Panchali",
        "Paths of Glory",
        "Patriot Games",
        "Patti Cakes",
        "Patty Hearst",
        "Pauly Shore is Dead",
        "Paycheck",
        "Pecker",
        "Pee Wee's Big Adventure",
        "Peeping Tom",
        "Penn and Teller Get Killed",
        "People vs Larry Flynt, The",
        "Perfect Blue",
        "Perfect Host, The",
        "Perfume The Story of a Murderer",
        "Persona",
        "Pet Sematary",
        "Phantasm (Series)",
        "Phantom of the Paradise",
        "Phenomena",
        "Philomena",
        "Pi",
        "Piano Teacher, The",
        "Picnic at Hanging Rock",
        "Picture of Dorian Gray, The",
        "Pieta",
        "Pigeon Sat on a Branch Reflecting on Existence, A",
        "Pink Flamingos",
        "Piranha (Series)",
        "Planet of the Apes",
        "Platoon",
        "Pola X",
        "Poltergeist",
        "Polyester",
        "Pontypool",
        "Pootie Tang",
        "Porco Rosso",
        "Possessor",
        "Postman Always Rings Twice, The",
        "Poughkeepsie Tapes, The",
        "Predator",
        "Predators",
        "Prep School",
        "Prestige, The",
        "Prevenge",
        "Primer",
        "Prince of Darkness",
        "Princess Bride, The",
        "Princess and the Frog, The",
        "Priscilla Queen of the Desert",
        "Prisoners",
        "Prom Night",
        "Prom Night 2",
        "Prophecy 2, The",
        "Prophecy 3, The",
        "Prophecy, The",
        "Prowler, The",
        "Psycho",
        "Pulp Fiction",
        "Pump Up the Volume",
        "Pumpkinhead (Series)",
        "Punch-Drunk Love",
        "Punisher, The",
        "Puppet Master (Series)",
        "Puppet Master The Littlest Reich",
        "Purge 2: Anarchy, The",
        "Purge, The",
        "Purple Rain",
        "R100",
        "REC",
        "Race with the Devil",
        "Rachel Getting Married",
        "Raging Bull",
        "Raid 2, The",
        "Raid: Redemption, The",
        "Rambo 4",
        "Rare Exports",
        "Ratatouille",
        "Ravenous",
        "Raw",
        "Re-Animator",
        "Ready or Not",
        "Real Steel",
        "Reality",
        "Rear Window",
        "Rebel Without a Cause",
        "Red Dawn",
        "Red Hook Summer",
        "Red Rock West",
        "Red State",
        "Red White and Blue",
        "Redbelt",
        "Reform School Girls",
        "Reign of Fire",
        "Religulous",
        "Repo Man",
        "Repo: The Genetic Opera",
        "Repulsion",
        "Requiem for a Dream",
        "Reservoir Dogs",
        "Resident Evil (Series)",
        "Resolution",
        "Resurrect Dead",
        "Return of the Living Dead (Series)",
        "Revenge",
        "Rider, The",
        "Rififi",
        "Rise of the Planet of the Apes",
        "Risk",
        "Road Games",
        "Roadracers",
        "RoboCop",
        "Rock N Roll High School",
        "Rock, The",
        "Rocky",
        "Rocky 2",
        "Rocky 3",
        "Rocky 4",
        "Rocky 5",
        "Rocky 6",
        "Rocky Horror Picture Show, The",
        "Rogue",
        "Rollerball",
        "Rolling Thunder",
        "Romancing the Stone",
        "Room",
        "Room, The",
        "Root of All Evil?, The",
        "Rope",
        "Rosemary's Baby",
        "Royal Tenenbaums, The",
        "Rubber",
        "Rumble in the Bronx",
        "Rush Hour",
        "S1M0NE",
        "SLC Punk",
        "Safety Not Guaranteed",
        "Satan's Little Helper",
        "Saw (Series)",
        "Scanner Darkly, A",
        "Scanners",
        "Scare Me",
        "Scent of a Woman",
        "Schindler's List",
        "School of the Holy Beast",
        "Scott Pilgrim",
        "Scream (Series)",
        "Scream of Fear",
        "Secret Beyond the Door",
        "Secret, The",
        "Secretary",
        "Serbian Film, A",
        "Serenity",
        "Serial Mom",
        "Serious Man, A",
        "Session 9",
        "Sessions, The",
        "Set it Off",
        "Seven",
        "Sex and Fury",
        "Shadow of the Vampire",
        "Shaft",
        "Shallow Grave",
        "Shame",
        "Shape of Things, The",
        "Sharkboy and Lavagirl",
        "Shaun of the Dead",
        "Shawshank Redemption, The",
        "She's Gotta Have It",
        "Sherlock Holmes' Smarter Brother",
        "Shining, The",
        "Shock of the Future, The",
        "Shogun Assassin",
        "Shoot 'Em Up",
        "Shootist, The",
        "Shorts",
        "Showgirls",
        "Sideways",
        "Sightseers",
        "Signal, The",
        "Silence of the Lambs",
        "Silent Night, Deadly Night (Series)",
        "Silent Running",
        "Simple Plan, A",
        "Sin City",
        "Singing Detective, The",
        "Sisters",
        "Skeleton Twins, The",
        "Skin I Live In, The",
        "Sky Crawlers, The",
        "Skyscraper",
        "Sleepaway Camp (Series)",
        "Sleepers",
        "Sleepy Hollow",
        "Slice",
        "Slither",
        "Slumdog Millionaire",
        "Small Soldiers",
        "Smash and Grab: The Story of the Pink Panthers",
        "Smokey and the Bandit",
        "Sneakers",
        "Snow White and the Seven Dwarfs",
        "So I Married an Axe Murderer",
        "Social Network, The",
        "Society",
        "Solaris",
        "Sonny",
        "Sorcerer",
        "Sorry to Bother You",
        "Soul Man",
        "Sound of Metal",
        "South Park",
        "Southland Tales",
        "Soylent Green",
        "Space Jam",
        "Specials, The",
        "Species (Series)",
        "Spider",
        "Spider-Man Into the Spider-Verse",
        "Spiral",
        "Spirit, The",
        "Spirited Away",
        "Spring",
        "Spring Breakers",
        "Spun",
        "Spy Kids",
        "Spy Kids 2",
        "Stage Fright (Deliria)",
        "Stake Land",
        "Stand By Me",
        "Starcrash",
        "Starman",
        "Starship Troopers",
        "Steal This Film 2",
        "Stepford Wives, The",
        "Stop! Or My Mom Will Shoot",
        "Storytelling",
        "Straight Outta Compton",
        "Straight Story, The",
        "Stranger Than Fiction",
        "Strangers on a Train",
        "Straw Dogs",
        "Stuck",
        "Stuff, The",
        "Sucker Punch",
        "Sugar and Spice",
        "Sukiyaki Western Django",
        "Sum of All Fears, The",
        "Summer of 84",
        "Sun Choke",
        "Sun Don’t Shine",
        "Sunshine",
        "Super",
        "Super 8",
        "Super Dark Times",
        "Super Fly",
        "Suspiria",
        "Suspiria (2018)",
        "Sweeney Todd",
        "Sweet Sweetback's Baadasssss Song",
        "Swiss Army Man",
        "Switchblade Sisters",
        "TFW NO GF",
        "Taken",
        "Taking of Deborah Logan, The",
        "Tale of Two Sisters, A",
        "Tales from Earthsea",
        "Tales from the Hood",
        "Tammy and the T-Rex",
        "Tangerine",
        "Tank Girl",
        "Tanna",
        "Taxi Driver",
        "Taxidermia",
        "Team America",
        "Teeth",
        "Tenant, The",
        "Tenebre",
        "Terminal, The",
        "Terminator",
        "Terminator 2",
        "Terminator 3",
        "Tesis",
        "Texas Chainsaw Massacre (Leatherface Series)",
        "Thank You for Smoking",
        "That Obscure Object of Desire",
        "The Amityville Horror (Series)",
        "The Evil Dead (Series)",
        "The Exorcist (Series)",
        "The Eye (Series)",
        "The Howling (Series)",
        "The Living Dead (Series)",
        "The Omen (Series)",
        "Theater of Blood",
        "Thelma and Louise",
        "Theodore Rex",
        "They Came Together",
        "They Live",
        "They Shoot Horses, Don't They?",
        "Thief",
        "Thing, The",
        "Thinner",
        "Third Man, The",
        "Thirteenth Floor, The",
        "This Film Is Not Yet Rated",
        "This Is Spinal Tap",
        "This Must Be the Place",
        "This is the End",
        "Thoroughbreds",
        "Three Colors Blue",
        "Three Colors Red",
        "Three Colors White",
        "Three O’Clock High",
        "Thriller: A Cruel Picture",
        "Thunder and Lightning",
        "Tickled",
        "Tie Me Up Tie Me Down",
        "Tim's Vermeer",
        "Timecrimes",
        "Tingler, The",
        "To Die For",
        "Toad Road",
        "Tokyo Drifter",
        "Tokyo Gore Police",
        "Tomboy",
        "Top Gun",
        "Total Recall",
        "Touch of Evil",
        "Town Called Panic, A",
        "Toxic Avenger, The",
        "Tragedy Girls",
        "Train to Busan",
        "Training Day",
        "Trainspotting",
        "Transsiberian",
        "Trash Humpers",
        "Tremors",
        "Trial, The",
        "Triangle",
        "Tribe (Plemya), The",
        "Trick 'r Treat",
        "Trip, The",
        "Triplets of Belleville, The",
        "Troll 2",
        "Troll Hunter",
        "Tron",
        "Trouble Every Day",
        "Trouble with Harry, The",
        "True Romance",
        "Truman",
        "Tucker and Dale vs Evil",
        "Tumbbad",
        "Tusk",
        "Twilight Zone The Movie",
        "Twin Peaks Fire Walk With Me",
        "Two Thousand Maniacs",
        "Two-Lane Blacktop",
        "Tyrannosaur",
        "Unbreakable",
        "Uncut Gems",
        "Under the Silver Lake",
        "Under the Skin",
        "United States of Leland, The",
        "Untamed, The",
        "Untouchables, The",
        "Up in Smoke",
        "Up!",
        "Upgrade",
        "Upstream Color",
        "Used Cars",
        "VHS (Series)",
        "Valentine",
        "Valhalla Rising",
        "Vampire Girl vs Frankenstein Girl",
        "Vampire's Kiss",
        "Vanishing Point",
        "Vanya on 42nd Street",
        "Verdict, The",
        "Vertigo",
        "Victor Crowley",
        "Videodrome",
        "Village of the Damned",
        "Village, The",
        "Visitor Q",
        "Voices, The",
        "W.",
        "Waco",
        "Wag the Dog",
        "Wages of Fear, The",
        "Waiting for Guffman",
        "Wall Street",
        "Walmart",
        "Ward, The",
        "Warriors, The",
        "Watchmen",
        "Wayne's World",
        "We Are What We Are",
        "We Need to Talk About Kevin",
        "Weather Man, The",
        "Welcome to the Dollhouse",
        "Wet Hot American Summer",
        "What Dreams May Come",
        "What Ever Happened to Baby Jane?",
        "What Have I Done to Deserve This",
        "What We Do In the Shadows",
        "Whatever Works",
        "When Harry Met Sally",
        "When a Stranger Calls",
        "When a Stranger Calls Back",
        "Whiskey Mountain",
        "Whisper of the Heart",
        "White Dog",
        "White Girl",
        "White God",
        "Who Framed Roger Rabbit",
        "Who's Afraid of Virginia Woolf",
        "Wicker Man, The",
        "Wiener Dog",
        "Wild Angels, The",
        "Wild Style",
        "Wild at Heart",
        "Willard",
        "Willow",
        "Willow Creek",
        "Wind River",
        "Windy City Heat",
        "Wishmaster (Series)",
        "Witch Who Came From the Sea, The",
        "Witch, The",
        "Witches, The",
        "Wizard of Gore, The",
        "Wizard of Oz, The",
        "Wolf Creek",
        "Wolf Man, The",
        "Woman in Black, The",
        "Woman, The",
        "Wonderful Horrible Life of Leni Reifenstahl, The",
        "World's End, The",
        "World's Greatest Dad",
        "Would You Rather",
        "Wrestler, The",
        "Wrong",
        "Wrong Man, The",
        "Wrong Turn (Series)",
        "XX",
        "Xtro",
        "Yellow Rose",
        "Yes, God, Yes",
        "Yoga Hosers",
        "You Were Never Really Here",
        "Young Frankenstein",
        "You’re Next",
        "Zack and Miri Make a Porno",
        "Zodiac",
        "Zombeavers",
        "Zombi 2",
        "Zombi Child",
        "eXistenZ",
    ]
}
